### ISSUE TITLE
Are BTU adapters compatible with Charybdis 4x6 version?

### ISSUE THREAD

**Issue by JGrzybowski** [Bastardkb/Charybdis#1]
As stated in the title, are BTU adapter files in 3x5 directory compatible with 4x6 files?
If so, it might be convinient to put them in the separete direcotry for BTU mod.

**Comment by LinuxBozo** [comment]
FWIW, I'm actively using the printable BTU mod on a 4x6 with great success. Works so much smoother than the roller bearings. Si3N4 ceramic bearing balls seem to work slightly smoother than stainless in the printable setup as well.
![IMG_0639](https://user-images.githubusercontent.com/723420/149630848-55f5edaa-d2fa-4de1-96ed-fe42546be6bc.jpg)

**Comment by bstiq** [comment]
Hopefully this covers everything.
There's also a version of the cheaper btu mod I modified to use screws rather than press fitting.

Thanks for the feedback LinuxBozo!

Regards,

**Comment by artlugovoy** [comment]
> FWIW, I'm actively using the printable BTU mod on a 4x6 with great success. Works so much smoother than the roller bearings. Si3N4 ceramic bearing balls seem to work slightly smoother than stainless in the printable setup as well. ![IMG_0639](https://user-images.githubusercontent.com/723420/149630848-55f5edaa-d2fa-4de1-96ed-fe42546be6bc.jpg)

Tnis is awesome! Please could you share the adapter STL?
