### ISSUE TITLE
Broken loft creates a 'crack' in the Charybdis thumb cluster

### ISSUE THREAD

**Issue by octarinesun** [Bastardkb/Charybdis#29]
Just formally submitting the issue from a discord discussion

files/3x5 nano/charybdisnano_v2_v187.step

![image](https://user-images.githubusercontent.com/9982066/224520248-ec52f68f-dff1-4d19-a3bb-1710631da400.png)
(Submitted by another user)

From cura:
![image](https://user-images.githubusercontent.com/9982066/224520564-18e38fba-0e34-4967-befa-7374bcd57ad2.png)

**Comment by bstiq** [comment]
fixed in latest version, closing
