### ISSUE TITLE
Undersized insert hole in 3x5 Charybdis STL

### ISSUE THREAD

**Issue by bjvanst** [Bastardkb/Charybdis#4]
The screw hole behind the thumb cluster in the STL for the 3x5 Charybdis is undersized compared to the rest.  It's closer to 5mm instead of 6mm.

![image](https://user-images.githubusercontent.com/46006744/140256801-c345ff58-724e-4957-aedd-e0035aa5895a.png)

**Comment by bstiq** [comment]
good catch. fixed ! thank you.
