### ISSUE TITLE
Add more tenting options for 3x6

### ISSUE THREAD

**Issue by dudicoco** [Bastardkb/Charybdis#45]
Hi,

Currently the 3x5 has multiple tenting options (5, 15 and 30 degrees), while the 3x6 only has 30 degrees tents.

Would it be possible to add 5 and 15 degrees tent stl files for the 3x6 as well?

Thanks

**Comment by bstiq** [comment]
Hey,

At the moment we don't have any design files for 5 and 15 degree tents.
If you'd like to create them you can use the plate files and we'd gladly accept a PR.

Regards,
