### ISSUE TITLE
Charybdis 4x6 tent, indented version does not match version in file

### ISSUE THREAD

**Issue by jeroenvanwijgerden** [Bastardkb/Charybdis#46]
Minor detail, I would understand you if you were to ignore this.

[https://github.com/Bastardkb/Charybdis/blob/main/files/4x6/tent_alien_30deg_v127.stl](https://github.com/Bastardkb/Charybdis/blob/main/files/4x6/tent_alien_30deg_v127.stl)

File says v127, indentation says v1_124.

![screenshot](https://github.com/user-attachments/assets/d4d9fde6-1f1e-440f-9c3f-c18814f86c50)

**Comment by bstiq** [comment]
Hello,

Thanks for the notice.
The file name is based on the overall design (charybdis), so I must have done some changes on the Charybdis or plate as well before exporting the tent.
The number on the tent is for internal use, the file that's on github is always the latest version.
