### ISSUE TITLE
MK2 right case missing ?

### ISSUE THREAD

**Issue by secteur0** [Bastardkb/Charybdis#50]
Hi,

I can not find the stl file for the right case of MKZ as spécified in the README (https://github.com/Bastardkb/Charybdis/blob/main/readme.md?plain=1#L38). I only see the left case (https://github.com/Bastardkb/Charybdis/blob/main/files/4x6/MK2/charybdis_v4_247.stl). Normal ?

Thank you for your hard work.

**Comment by bstiq** [comment]
Hey, 

To get the right case, you can simply mirror it. All the 3d models are reversible.
